apiVersion: apps/v1
kind: Deployment
metadata:
  name: magnus-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magnus-api
  template:
    metadata:
      labels:
        app: magnus-api
    spec:
      containers:
        - name: magnus-api
          image: amankashyap07/magnus-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_USER
              value: "amankashyap"
            - name: POSTGRES_DB
              value: "ci_cd_engine"
            - name: FRONTEND_URL
              value: "http://129.154.39.198/ci/"
            - name: JWT_SECRET
              value: "aman123"
            # Note: Secrets should ideally use kubernetes Secret resources.
            - name: GITHUB_CLIENT_ID
              value: "Ov23liW688DnyJEBbQ5I"
            - name: GITHUB_CLIENT_SECRET
              value: "c9934dc0a53522b9b784fa04562baa0d541fc28b"
            - name: GITHUB_WEBHOOK_SECRET
              value: "aman123"
            - name: GITHUB_TOKEN
              value: "your_github_personal_access_token_here"
---
apiVersion: v1
kind: Service
metadata:
  name: magnus-api
spec:
  type: NodePort
  selector:
    app: magnus-api
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30501
